name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: ${{ github.repository }}

jobs:
  python-matrix:
    name: python-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ci/envs/py310.yaml
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ${{ matrix.env }}
      - name: Install
        python3 -m pip install -e .

      - name: Check and Log Environment
        run: |
          python -V
          python -c "import geopandas; geopandas.show_versions();"
          micromamba info
          micromamba list

      - name: Execute linters and test suites
        run: ./scripts/cibuild

